services:
  traefik:
    image: traefik:v2.11
    user: "{{ docker_user.id }}"
    volumes:
      - ./traefik:/etc/traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on:
      - docker_proxy
    networks:
      - default
      - traefik
      - proxy_private

  docker_proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - INFO=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy_private
    tmpfs:
      - /run
    logging:
      driver: none
  certs:
    image: slocomptech/traefik-cert-extract:latest
    restart: unless-stopped
    networks: []
    volumes:
      - ./traefik:/data:ro
      - ./certs:/config/certs
    logging:
      driver: none

  authentik-proxy:
    image: ghcr.io/goauthentik/proxy
    environment:
      - AUTHENTIK_HOST=https://{{ vault_authentik_domain }}
      - AUTHENTIK_TOKEN={{ vault_authentik_proxy_token }}
    extra_hosts:
      - "{{ vault_authentik_domain }}:10.111.0.2"
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.http.routers.authentik-proxy.rule=PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-proxy.tls.certresolver=le"
      - "traefik.http.middlewares.authentik.forwardauth.address=http://authentik-proxy:9000/outpost.goauthentik.io/auth/traefik"
      - "traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version"
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
  proxy_private:
    internal: true
